# Generated by Django 6.1.1 on 2026-09-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=13, verbose_name='شماره موبایل')),
                ('service', models.CharField(choices=[('web_design', 'طراحی سایت'), ('custom_development', 'توسعه اختصاصی'), ('seo_performance', 'سئو و بهینه\u200cسازی عملکرد'), ('automation', 'اتوماسیون'), ('consultation', 'مشاوره'), ('other', 'سایر')], max_length=32, verbose_name='نوع خدمت')),
                ('project_description', models.TextField(verbose_name='توضیحات پروژه')),
                ('website_url', models.URLField(blank=True, verbose_name='آدرس وب\u200cسایت')),
                ('estimated_budget', models.CharField(blank=True, max_length=150, verbose_name='بودجه تقریبی')),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'تماس تلفنی'), ('whatsapp', 'واتساپ'), ('telegram', 'تلگرام')], default='phone', max_length=16, verbose_name='روش ارتباط ترجیحی')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewed', 'بررسی\u200cشده'), ('contacted', 'تماس گرفته\u200cشده'), ('converted', 'تبدیل\u200cشده'), ('rejected', 'ردشده')], default='new', max_length=16, verbose_name='وضعیت')),
                ('internal_note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست\u200cهای همکاری',
                'ordering': ('-created_at',),
            },
        ),
    ]
