version: '3.9'

services:
  web:
    build: .
    command: sh -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=dv+8u%c&p$$z(bz%@i+ok-g@f@^13c1$q67p($k0i1u2w-)o(gp"


  db:
    image: postgres:18
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
