# Generated by Django 6.1.1 on 2026-09-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_post_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'نوشته', 'verbose_name_plural': 'نوشته ها'},
        ),
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
