"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from django.templatetags.static import static
from django.urls import reverse_lazy
from environs import Env
from django.core.exceptions import ImproperlyConfigured


env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Docker Compose supplies these variables through env_file. Read the same local
# file for direct manage.py runs without overriding variables from the host.
env.read_env(BASE_DIR / '.env', recurse=False, override=False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=False)
PRODUCTION = env.str('DJANGO_ENV', default='development') == 'production'
if PRODUCTION and (DEBUG or len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 5
                   or SECRET_KEY.startswith(('django-insecure-', 'replace-with-'))):
    raise ImproperlyConfigured('Production requires DEBUG=False and a strong DJANGO_SECRET_KEY.')

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'] if DEBUG else [])
CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])
if PRODUCTION and (not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS or not CSRF_TRUSTED_ORIGINS):
    raise ImproperlyConfigured('Production requires explicit hosts and HTTPS CSRF origins.')
if PRODUCTION and any(not origin.startswith('https://') for origin in CSRF_TRUSTED_ORIGINS):
    raise ImproperlyConfigured('Production CSRF origins must use HTTPS.')

# Safe only behind the supplied proxy, which overwrites X-Forwarded-Proto.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if PRODUCTION else None
SECURE_SSL_REDIRECT = env.bool('DJANGO_SECURE_SSL_REDIRECT', default=PRODUCTION)
SECURE_REDIRECT_EXEMPT = [r'^healthz/$']
SESSION_COOKIE_SECURE = PRODUCTION
CSRF_COOKIE_SECURE = PRODUCTION
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = env.int('DJANGO_SECURE_HSTS_SECONDS', default=3600 if PRODUCTION else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('DJANGO_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('DJANGO_HSTS_PRELOAD', default=False)
SECURE_REFERRER_POLICY = 'same-origin'

# Application definition

INSTALLED_APPS = [
    'unfold',
    # all auth
    'allauth',
    'allauth.account',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # apps
    'blog',
    'accounts',
    'pages',
    'portfolio',
    'leads',
    'tools',
    'seo',
]

UNFOLD = {
    'SITE_TITLE': 'مدیریت سیتارو',
    'SITE_HEADER': 'سیتارو',
    'SITE_SUBHEADER': 'مدیریت پروژه و محتوا',
    'SITE_ICON': lambda request: static('images/sitaro-logo.svg'),
    'SITE_URL': '/',
    'DASHBOARD_CALLBACK': 'config.admin_dashboard.dashboard_callback',
    'SITE_VIEWS': [('seo/', 'seo_overview', 'config.admin_seo.SEOOverviewView')],
    'STYLES': [lambda request: static('css/admin-dashboard.css')],
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': False,
        'navigation': [
            {
                'title': 'نمای کلی',
                'items': [
                    {'title': 'داشبورد', 'icon': 'dashboard', 'link': reverse_lazy('admin:index')},
                ],
            },
            {
                'title': 'مشتریان و پروژه‌ها',
                'separator': True,
                'items': [
                    {'title': 'درخواست‌ها', 'icon': 'inbox',
                     'link': reverse_lazy('admin:leads_contactrequest_changelist'),
                     'permission': lambda request: request.user.has_perm(
                         'leads.view_contactrequest') or request.user.has_perm('leads.change_contactrequest')},
                    {'title': 'پروژه‌های مشتریان', 'icon': 'account_tree',
                     'link': reverse_lazy('admin:leads_clientproject_changelist'),
                     'permission': lambda request: request.user.has_perm(
                         'leads.view_clientproject') or request.user.has_perm('leads.change_clientproject')},
                ],
            },
            {
                'title': 'محتوا و ابزارها',
                'separator': True,
                'items': [
                    {'title': 'نمونه‌کارها', 'icon': 'work', 'link': reverse_lazy('admin:portfolio_project_changelist'),
                     'permission': lambda request: request.user.has_perm(
                         'portfolio.view_project') or request.user.has_perm('portfolio.change_project')},
                    {'title': 'بلاگ', 'icon': 'article', 'link': reverse_lazy('admin:blog_post_changelist'),
                     'permission': lambda request: request.user.has_perm('blog.view_post') or request.user.has_perm(
                         'blog.change_post')},
                    {'title': 'ابزارها', 'icon': 'construction', 'link': reverse_lazy('admin:tools_tool_changelist'),
                     'permission': lambda request: request.user.has_perm('tools.view_tool') or request.user.has_perm(
                         'tools.change_tool')},
                    {'title': 'دسته‌های ابزار', 'icon': 'category',
                     'link': reverse_lazy('admin:tools_toolcategory_changelist'),
                     'permission': lambda request: request.user.has_perm(
                         'tools.view_toolcategory') or request.user.has_perm('tools.change_toolcategory')},
                ],
            },
            {
                'title': 'دسترسی‌ها',
                'separator': True,
                'items': [
                    {'title': 'کاربران', 'icon': 'group', 'link': reverse_lazy('admin:accounts_customuser_changelist'),
                     'permission': lambda request: request.user.has_perm(
                         'accounts.view_customuser') or request.user.has_perm('accounts.change_customuser')},
                    {'title': 'گروه‌ها', 'icon': 'admin_panel_settings',
                     'link': reverse_lazy('admin:auth_group_changelist'),
                     'permission': lambda request: request.user.has_perm('auth.view_group') or request.user.has_perm(
                         'auth.change_group')},
                ],
            },
            {
                'title': 'بررسی سئو',
                'separator': True,
                'items': [
                    {'title': 'وضعیت سایت و سرچ کنسول', 'icon': 'monitoring',
                     'link': reverse_lazy('admin:seo_overview'),
                     'permission': lambda request: request.user.is_superuser},
                    {'title': 'سئوی صفحات ثابت', 'icon': 'web',
                     'link': reverse_lazy('admin:seo_staticpageseo_changelist'),
                     'permission': lambda request: request.user.has_perm('seo.view_staticpageseo')},
                    {'title': 'تنظیمات سئوی سایت', 'icon': 'tune',
                     'link': reverse_lazy('admin:seo_siteseosettings_changelist'),
                     'permission': lambda request: request.user.has_perm('seo.view_siteseosettings')},
                ],
            },
        ],
    },
    'COLORS': {
        'primary': {
            '50': '#effcf5',
            '100': '#dcf8e9',
            '200': '#b9f0d4',
            '300': '#83e1b5',
            '400': '#4dcb96',
            '500': '#20b37b',
            '600': '#0b9466',
            '700': '#087551',
            '800': '#095b41',
            '900': '#0a4936',
            '950': '#062b20',
        },
    },
}

# A URL-prefix property normally ends in a slash. Keep credentials outside git.
SITARO_GSC_SITE_URL = os.getenv('SITARO_GSC_SITE_URL', 'https://sitarogroup.ir/').strip()
SITARO_GSC_CREDENTIALS_FILE = os.getenv('SITARO_GSC_CREDENTIALS_FILE', '').strip()
SITARO_PUBLIC_SITE_URL = 'https://sitarogroup.ir/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    # all auth
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tools.context_processors.header_tools',
                'seo.context_processors.seo_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str('POSTGRES_DB', default='postgres'),
        'USER': env.str('POSTGRES_USER', default='postgres'),
        'PASSWORD': env.str('POSTGRES_PASSWORD', default=''),
        'HOST': env.str('POSTGRES_HOST', default='db'),
        'PORT': env.int('POSTGRES_PORT', default=5432),
        'CONN_MAX_AGE': env.int('DB_CONN_MAX_AGE', default=60),
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {'connect_timeout': 5, 'sslmode': env.str('POSTGRES_SSLMODE', default='prefer')},
    }
}

# Password validation
if PRODUCTION and (not DATABASES['default']['PASSWORD']
                   or DATABASES['default']['PASSWORD'].startswith('replace-with-')):
    raise ImproperlyConfigured('A real POSTGRES_PASSWORD is required in production.')

# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = Path(env.str('DJANGO_STATIC_ROOT', default=str(BASE_DIR / 'staticfiles')))

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

smtp_host = env.str('EMAIL_HOST', default='')
smtp_port = env.int('EMAIL_PORT', default=587)
smtp_user = env.str('EMAIL_HOST_USER', default='')
smtp_password = env.str('EMAIL_HOST_PASSWORD', default='')
smtp_tls = env.bool('EMAIL_USE_TLS', default=True)
smtp_ssl = env.bool('EMAIL_USE_SSL', default=False)
smtp_timeout = env.int('EMAIL_TIMEOUT', default=10)
DEFAULT_FROM_EMAIL = env.str('DEFAULT_FROM_EMAIL', default='webmaster@localhost')
SERVER_EMAIL = env.str('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)
if smtp_tls and smtp_ssl:
    raise ImproperlyConfigured('EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be enabled.')
if PRODUCTION and (not smtp_host or DEFAULT_FROM_EMAIL.endswith('@localhost')):
    raise ImproperlyConfigured('Production requires EMAIL_HOST and DEFAULT_FROM_EMAIL.')
if smtp_host:
    MAILERS['default'] = {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': smtp_host, 'port': smtp_port,
            'username': smtp_user, 'password': smtp_password,
            'use_tls': smtp_tls, 'use_ssl': smtp_ssl, 'timeout': smtp_timeout,
        },
    }

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
]

AUTH_USER_MODEL = 'accounts.CustomUser'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# media files
MEDIA_URL = '/media/'
MEDIA_ROOT = env.str('DJANGO_MEDIA_ROOT', default=str(BASE_DIR / 'media'))

LOGGING = {
    'version': 1, 'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False}},
}

# Public contact channels. Keep blank until the real Sitaro details are ready.
SITARO_CONTACT_PHONE = "09197736862"
SITARO_WHATSAPP_URL = "https://wa.me/989197736862"
SITARO_TELEGRAM_URL = "https://t.me/989197736862"


ACCOUNT_LOGIN_METHODS={'email' , 'username' , }

