# Generated by Django 6.1.1 on 2026-09-18 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='نام پروژه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='آدرس خوانا')),
                ('industry', models.CharField(max_length=120, verbose_name='حوزه فعالیت')),
                ('summary', models.CharField(max_length=240, verbose_name='خلاصه یک\u200cخطی')),
                ('cover', models.ImageField(upload_to='portfolio/covers/%Y/%m/', verbose_name='تصویر اصلی')),
                ('cover_alt', models.CharField(max_length=200, verbose_name='متن جایگزین تصویر اصلی')),
                ('introduction', models.TextField(verbose_name='معرفی')),
                ('challenge', models.TextField(verbose_name='مسئله')),
                ('solution', models.TextField(verbose_name='راه\u200cحل')),
                ('completed_work', models.TextField(help_text='هر مورد را در یک خط جداگانه وارد کنید.', verbose_name='کارهای انجام\u200cشده')),
                ('result', models.TextField(blank=True, verbose_name='نتیجه')),
                ('website_url', models.URLField(blank=True, verbose_name='لینک سایت')),
                ('meta_title', models.CharField(blank=True, help_text='اختیاری؛ در صورت خالی بودن، نام پروژه استفاده می\u200cشود.', max_length=70, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, help_text='اختیاری؛ در صورت خالی بودن، خلاصه یک\u200cخطی استفاده می\u200cشود.', max_length=160, verbose_name='توضیحات متا')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/%Y/%m/', verbose_name='تصویر')),
                ('alt_text', models.CharField(max_length=200, verbose_name='متن جایگزین تصویر')),
                ('caption', models.CharField(blank=True, max_length=240, verbose_name='توضیح تصویر')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
