# Generated by Django 6.1.1 on 2026-09-25 13:16

import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='اگر خالی باشد، عنوان خود محتوا استفاده می\u200cشود.', max_length=200, verbose_name='عنوان اختصاصی سئو')),
                ('meta_description', models.TextField(blank=True, help_text='اگر خالی باشد، از خلاصه یا ابتدای محتوای صفحه استفاده می\u200cشود.', verbose_name='توضیحات متا')),
                ('focus_keyword', models.CharField(blank=True, help_text='فقط برای بررسی داخلی محتواست و به meta keywords تبدیل نمی\u200cشود.', max_length=150, verbose_name='عبارت کلیدی هدف')),
                ('canonical_url', models.URLField(blank=True, help_text='در صورت خالی بودن، از آدرس اصلی همین صفحه ساخته می\u200cشود.', verbose_name='نشانی canonical')),
                ('robots_index', models.BooleanField(default=True, help_text='با غیرفعال\u200cکردن، دستور noindex تولید می\u200cشود.', verbose_name='اجازه ایندکس')),
                ('robots_follow', models.BooleanField(default=True, help_text='با غیرفعال\u200cکردن، دستور nofollow تولید می\u200cشود.', verbose_name='اجازه دنبال\u200cکردن پیوندها')),
                ('og_title', models.CharField(blank=True, help_text='اگر خالی باشد، عنوان سئو استفاده می\u200cشود.', max_length=200, verbose_name='عنوان شبکه\u200cهای اجتماعی')),
                ('og_description', models.TextField(blank=True, help_text='اگر خالی باشد، توضیحات متا استفاده می\u200cشود.', verbose_name='توضیح شبکه\u200cهای اجتماعی')),
                ('og_image', models.ImageField(blank=True, help_text='اگر خالی باشد، تصویر شاخص محتوا یا تصویر پیش\u200cفرض سایت استفاده می\u200cشود.', upload_to='seo/og/%Y/%m/', verbose_name='تصویر شبکه\u200cهای اجتماعی')),
                ('schema_mode', models.CharField(choices=[('auto', 'خودکار'), ('custom', 'اختصاصی'), ('disabled', 'غیرفعال')], default='auto', help_text='خودکار، اختصاصی یا غیرفعال.', max_length=12, verbose_name='حالت اسکیما')),
                ('custom_schema', models.JSONField(blank=True, help_text='JSON-LD معتبر؛ فقط در حالت اختصاصی رندر می\u200cشود.', null=True, validators=[seo.models.validate_schema], verbose_name='اسکیمای اختصاصی')),
                ('seo_updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش تنظیمات سئو')),
                ('page_key', models.CharField(choices=[('home', 'صفحه اصلی'), ('contact', 'تماس'), ('tools', 'فهرست ابزارها'), ('portfolio_index', 'فهرست نمونه\u200cکارها'), ('blog_index', 'فهرست بلاگ')], max_length=24, unique=True, verbose_name='صفحه')),
            ],
            options={
                'verbose_name': 'سئوی صفحه ثابت',
                'verbose_name_plural': 'سئوی صفحات ثابت',
            },
        ),
        migrations.CreateModel(
            name='SiteSEOSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='گروه سیتارو', max_length=160, verbose_name='نام سایت')),
                ('default_seo_title', models.CharField(default='گروه سیتارو | طراحی سایت اختصاصی، جنگو، وردپرس و سئو', max_length=200, verbose_name='عنوان پیش\u200cفرض')),
                ('default_meta_description', models.TextField(default='طراحی و توسعه وب\u200cسایت\u200cهای اختصاصی با Django و WordPress، سئو تکنیکال و بهینه\u200cسازی سرعت توسط گروه سیتارو.', verbose_name='توضیح پیش\u200cفرض')),
                ('site_url', models.URLField(default='https://sitarogroup.ir/', verbose_name='آدرس اصلی سایت')),
                ('organization_name', models.CharField(default='گروه سیتارو', max_length=160, verbose_name='نام سازمان')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='نام حقوقی')),
                ('organization_logo', models.ImageField(blank=True, upload_to='seo/site/', verbose_name='لوگوی سازمان')),
                ('organization_description', models.TextField(blank=True, verbose_name='توضیح سازمان')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='تلفن تماس')),
                ('social_links', models.JSONField(blank=True, default=list, help_text='فهرست JSON از آدرس\u200cهای واقعی شبکه\u200cهای اجتماعی.', verbose_name='پیوندهای شبکه\u200cهای اجتماعی')),
                ('default_og_image', models.ImageField(blank=True, upload_to='seo/site/', verbose_name='تصویر پیش\u200cفرض شبکه\u200cهای اجتماعی')),
                ('default_og_type', models.CharField(default='website', max_length=30, verbose_name='نوع پیش\u200cفرض Open Graph')),
            ],
            options={
                'verbose_name': 'تنظیمات سئوی سایت',
                'verbose_name_plural': 'تنظیمات سئوی سایت',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='seo_single_site_settings')],
            },
        ),
    ]
