# Generated by Django 6.1.1 on 2026-09-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_seed_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpageseo',
            name='focus_keyword',
        ),
        migrations.RemoveField(
            model_name='staticpageseo',
            name='seo_updated_at',
        ),
        migrations.AddField(
            model_name='staticpageseo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
    ]
