# Generated by Django 5.2.17 on 2026-09-19 20:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='آدرس خوانا')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی ابزار',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای ابزار',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True, verbose_name='آدرس خوانا')),
                ('short_description', models.CharField(max_length=280, verbose_name='توضیح کوتاه')),
                ('icon', models.FileField(blank=True, help_text='اختیاری؛ فرمت SVG، PNG یا WebP.', upload_to='tools/icons/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(('svg', 'png', 'webp'))], verbose_name='آیکون')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('coming_soon', 'به\u200cزودی'), ('disabled', 'غیرفعال')], default='coming_soon', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ابزار شاخص')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='tools.toolcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'ابزار',
                'verbose_name_plural': 'ابزارها',
                'ordering': ('order', 'title'),
            },
        ),
    ]
