# Generated by Django 6.1.1 on 2026-09-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_activate_schema_generator'),
        ('tools', '0004_activate_website_analyzer'),
    ]

    operations = [
    ]
