# Generated by Django 6.1.1 on 2026-09-25 13:16

import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_restore_tool_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='در صورت خالی بودن، از آدرس اصلی همین صفحه ساخته می\u200cشود.', verbose_name='نشانی canonical'),
        ),
        migrations.AddField(
            model_name='tool',
            name='custom_schema',
            field=models.JSONField(blank=True, help_text='JSON-LD معتبر؛ فقط در حالت اختصاصی رندر می\u200cشود.', null=True, validators=[seo.models.validate_schema], verbose_name='اسکیمای اختصاصی'),
        ),
        migrations.AddField(
            model_name='tool',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='فقط برای بررسی داخلی محتواست و به meta keywords تبدیل نمی\u200cشود.', max_length=150, verbose_name='عبارت کلیدی هدف'),
        ),
        migrations.AddField(
            model_name='tool',
            name='meta_description',
            field=models.TextField(blank=True, help_text='اگر خالی باشد، از خلاصه یا ابتدای محتوای صفحه استفاده می\u200cشود.', verbose_name='توضیحات متا'),
        ),
        migrations.AddField(
            model_name='tool',
            name='og_description',
            field=models.TextField(blank=True, help_text='اگر خالی باشد، توضیحات متا استفاده می\u200cشود.', verbose_name='توضیح شبکه\u200cهای اجتماعی'),
        ),
        migrations.AddField(
            model_name='tool',
            name='og_image',
            field=models.ImageField(blank=True, help_text='اگر خالی باشد، تصویر شاخص محتوا یا تصویر پیش\u200cفرض سایت استفاده می\u200cشود.', upload_to='seo/og/%Y/%m/', verbose_name='تصویر شبکه\u200cهای اجتماعی'),
        ),
        migrations.AddField(
            model_name='tool',
            name='og_title',
            field=models.CharField(blank=True, help_text='اگر خالی باشد، عنوان سئو استفاده می\u200cشود.', max_length=200, verbose_name='عنوان شبکه\u200cهای اجتماعی'),
        ),
        migrations.AddField(
            model_name='tool',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='با غیرفعال\u200cکردن، دستور nofollow تولید می\u200cشود.', verbose_name='اجازه دنبال\u200cکردن پیوندها'),
        ),
        migrations.AddField(
            model_name='tool',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='با غیرفعال\u200cکردن، دستور noindex تولید می\u200cشود.', verbose_name='اجازه ایندکس'),
        ),
        migrations.AddField(
            model_name='tool',
            name='schema_mode',
            field=models.CharField(choices=[('auto', 'خودکار'), ('custom', 'اختصاصی'), ('disabled', 'غیرفعال')], default='auto', help_text='خودکار، اختصاصی یا غیرفعال.', max_length=12, verbose_name='حالت اسکیما'),
        ),
        migrations.AddField(
            model_name='tool',
            name='seo_title',
            field=models.CharField(blank=True, help_text='اگر خالی باشد، عنوان خود محتوا استفاده می\u200cشود.', max_length=200, verbose_name='عنوان اختصاصی سئو'),
        ),
        migrations.AddField(
            model_name='tool',
            name='seo_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش تنظیمات سئو'),
        ),
    ]
